base: &aliossbase
  inittype: 1 # 初始化类型 1:OSS域名 2:自定义域名 3:STS 4:代理服务器 5:带账号密码的代理服务器
  access:
    key:
      id: "1111"
      secret: "1111"
  endpoint:
    protocol: "http"
    domain: "oss-cn-shenzhen.aliyuncs.com"
  security:
    token: "1111"
  proxy:
    url: "http://127.0.0.1:8888"
    user: "1111"
    password: "1111"
  bucket:
    name: "1111"
    domain: "http://pic.xxx.com/"
deva01:
  <<: *aliossbase
