aliyun:
    base: &aliyunbase
        region:
            id: "cn-hangzhou"
        access:
            key: "1111"
            secret: "1111"
    deva01:
        <<: *aliyunbase
baidu:
    base: &baidubase
        access:
            key: "1111"
            secret: "1111"
    deva01:
        <<: *baidubase
tencent:
    base: &tencentbase
        region:
            id: "ap-guangzhou"
        secret:
            id: "1111"
            key: "1111"
    deva01:
        <<: *tencentbase
