base: &serverbase
  host: "127.0.0.1"
  port: 8080
  type: "rpc"
  timeout:
    request: 3.0
    controller: 3.0
    action: 3.0
  mvc:
    block:
      accept:
        index: "默认"
        frontend: "前端"
        backend: "后端"
dev:
  a01api:
    <<: *serverbase
    type: "api"
