base: &serverbase
  host: "127.0.0.1"
  port: 8080
  type: "rpc"
  timeout:
    request: 3.0
    controller: 3.0
    action: 3.0
  mvc:
    module:
      default: "index"
      accept:
        - "index"
    controller:
      default: "index"
    action:
      default: "index"
dev:
  a01api:
    <<: *serverbase
    type: "api"
